version: "3.8"

networks: bot

services:
    tester_1:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_2:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_3:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_4:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_5:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_6:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_7:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_8:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_9:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_10:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_11:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
    tester_12:
        image: tester:1.0
        restart: always
        environment:
            DATABASE_URL: mongodb://binance_user:msmhassan1@bot_mongo:27017/binance
        networks:
            - bot
